In [1]:
from ckine.plot_model_prediction import surf_IL2Rb, pstat

In [2]:
surf = surf_IL2Rb()
surf.calc_1()

(array([1.        , 0.99999755, 0.99998891, 0.99995949, 0.9999346 ,
        0.99990784, 0.99989299]),
 array([1.        , 0.99972256, 0.9987594 , 0.99554488, 0.99290335,
        0.99010643, 0.98856112]),
 array([1.        , 0.99999763, 0.99998938, 0.99995917, 0.99993481,
        0.99990779, 0.99989225]),
 array([1.        , 0.99972477, 0.99875144, 0.99548695, 0.99277342,
        0.98988822, 0.98830016]),
 array([1.        , 0.99999888, 0.99998971, 0.99986046, 0.999549  ,
        0.9990696 , 0.9987972 ]),
 array([1.        , 0.99980515, 0.99910036, 0.99647003, 0.9939546 ,
        0.99113956, 0.9895829 ]),
 array([1.        , 0.99999888, 0.99998971, 0.99986046, 0.999549  ,
        0.9990696 , 0.9987972 ]),
 array([1.        , 0.99980515, 0.99910036, 0.99647003, 0.9939546 ,
        0.99113956, 0.9895829 ]))

In [3]:
surf.calc_2()

(array([1.        , 0.99999893, 0.99999564, 0.99998656, 0.99998045,
        0.99997662, 0.99997601]),
 array([1.        , 0.99987988, 0.99951244, 0.99850086, 0.99782003,
        0.9974087 , 0.99732397]),
 array([1.        , 0.99999894, 0.99999581, 0.9999866 , 0.99997965,
        0.99997715, 0.99997626]),
 array([1.        , 0.99988051, 0.99951007, 0.99849705, 0.99781163,
        0.99737986, 0.99730719]),
 array([1.        , 0.99999926, 0.99999029, 0.99986641, 0.99963364,
        0.99941896, 0.99937044]),
 array([1.        , 0.99992145, 0.99970061, 0.99910495, 0.9986222 ,
        0.99827824, 0.99820525]),
 array([1.        , 0.99999926, 0.99999029, 0.99986641, 0.99963364,
        0.99941896, 0.99937044]),
 array([1.        , 0.99992145, 0.99970061, 0.99910495, 0.9986222 ,
        0.99827824, 0.99820525]))

In [4]:
act = pstat()
act.calc_1()

[nan nan nan nan nan nan nan nan]
nan
[nan nan nan nan nan nan nan nan]
nan


TypeError: 'numpy.float64' object is not iterable