In [1]:
import numpy as np

In [2]:
tensor = np.random.rand(2,3,4)
tensor

array([[[0.01729587, 0.23218691, 0.70242239, 0.61169816],
        [0.87904173, 0.13135397, 0.47836022, 0.69071776],
        [0.55130481, 0.99702826, 0.18412538, 0.56819259]],

       [[0.65557678, 0.0781939 , 0.38061743, 0.58692927],
        [0.58287652, 0.5300814 , 0.63276904, 0.9211471 ],
        [0.25602048, 0.60368495, 0.89087017, 0.36401205]]])

In [3]:
from ckine.Tensor_analysis import z_score_values
scored_tensor = z_score_values(tensor)
scored_tensor

Using numpy backend.
Using numpy backend.


array([[[0.06819704, 0.91550528, 2.76962817, 2.41190552],
        [3.79316   , 0.56680655, 2.06417601, 2.98052171],
        [2.05800282, 3.72187385, 0.68733402, 2.12104436]],

       [[2.58491746, 0.30831594, 1.50076187, 2.3142426 ],
        [2.5151751 , 2.28735849, 2.73046674, 3.97484921],
        [0.95571609, 2.25353617, 3.32558919, 1.35884506]]])

In [4]:
def z_score_old(A, subtract = True):
    '''Function that takes in the values tensor and z-scores it.'''
    B = np.zeros_like(A)
    for i in range(A.shape[2]):
        slice_face = A[:,:,i]
        mu = np.mean(slice_face)
        sigma = np.std(slice_face)
        if subtract is True:
            z_scored_slice = (slice_face - mu) / sigma
        elif subtract is False:
            z_scored_slice = slice_face / sigma
        B[:,:,i] = z_scored_slice
    return B

In [5]:
scored_old_tensor = z_score_old(tensor, subtract = False)
scored_old_tensor

array([[[0.06184013, 0.72594959, 3.07145785, 3.68888936],
        [3.14295007, 0.41068791, 2.09170902, 4.16542269],
        [1.97115043, 3.11728275, 0.80511861, 3.42652596]],

       [[2.3439673 , 0.24447902, 1.66431251, 3.53951879],
        [2.08403277, 1.65733879, 2.76688706, 5.55504328],
        [0.9153827 , 1.88746575, 3.89547685, 2.1952006 ]]])

In [6]:
#Slicing the tensor along the last dimension and finding the standard deviation
for i in range(tensor.shape[2]):
    std_new = np.std(scored_tensor[:,:,i])
    print(std_new)
#This is from the Numpy broadcasting function

1.2005977509566632
1.1952773691366987
0.8818427950596925
0.8051757179815182


In [7]:
#Slicing the tensor along the last dimension and finding the standard deviation
for i in range(tensor.shape[2]):
    std_old = np.std(scored_old_tensor[:,:,i])
    print(std_old)
#This is from the Numpy broadcasting function

1.0
1.0
1.0
0.9999999999999998


In [8]:
#Using the axis method
std_new = np.std(scored_tensor, axis=(0, 2))
std_new
#This is from the Numpy broadcasting function

array([1., 1., 1.])

In [9]:
#Using the axis method
std_old = np.std(scored_old_tensor, axis=(0, 2))
std_old
#This is from the hardcore slicing function.

array([1.36970012, 1.48187174, 1.05589773])