In [1]:
import numpy as np

In [2]:
tensor = np.random.rand(2,3,4)
tensor

array([[[0.39503151, 0.43104139, 0.27345228, 0.99610927],
        [0.16779887, 0.06091014, 0.39088709, 0.62807477],
        [0.86705089, 0.12368452, 0.28697726, 0.94797485]],

       [[0.85852942, 0.36675138, 0.35829993, 0.93587289],
        [0.02663264, 0.42216133, 0.7434559 , 0.84404902],
        [0.33790182, 0.70029435, 0.27305501, 0.08063525]]])

In [3]:
from ckine.Tensor_analysis import z_score_values
scored_tensor = z_score_values(tensor)
scored_tensor

Using numpy backend.
Using numpy backend.


array([[[1.41637844, 1.54549125, 0.9804583 , 3.57153205],
        [0.57760685, 0.20966834, 1.3455338 , 2.16199475],
        [2.74549049, 0.39164329, 0.90870483, 3.00173379]],

       [[3.07824194, 1.31498054, 1.28467803, 3.35555558],
        [0.09167638, 1.45318778, 2.55916626, 2.90543362],
        [1.06995592, 2.21746096, 0.86462046, 0.25532909]]])

In [4]:
def z_score_old(A, subtract = True):
    '''Function that takes in the values tensor and z-scores it.'''
    B = np.zeros_like(A)
    for i in range(A.shape[2]):
        slice_face = A[:,:,i]
        mu = np.mean(slice_face)
        sigma = np.std(slice_face)
        if subtract is True:
            z_scored_slice = (slice_face - mu) / sigma
        elif subtract is False:
            z_scored_slice = slice_face / sigma
        B[:,:,i] = z_scored_slice
    return B

In [5]:
scored_old_tensor = z_score_old(tensor)
scored_old_tensor

array([[[-0.14720608,  0.37854366, -0.69143219,  0.81014511],
        [-0.85700566, -1.36772945,  0.0193636 , -0.34855834],
        [ 1.3272263 , -1.07156097, -0.60956979,  0.65860086]],

       [[ 1.30060804,  0.07522444, -0.17787617,  0.62049957],
        [-1.29796228,  0.33664767,  2.15335131,  0.33140539],
        [-0.32566033,  1.64887464, -0.69383675, -2.07209258]]])