In [1]:
import numpy as np

In [6]:
tensor = np.random.rand(2,3,4)
tensor

array([[[0.43437855, 0.64347724, 0.89223073, 0.5478411 ],
        [0.01956257, 0.77807369, 0.03340146, 0.35637853],
        [0.99312845, 0.08211176, 0.80728772, 0.7322535 ]],

       [[0.45941606, 0.683191  , 0.33879455, 0.41325308],
        [0.87338172, 0.91684791, 0.33891053, 0.75720977],
        [0.47106976, 0.24873414, 0.0933682 , 0.5901137 ]]])

In [7]:
from ckine.Tensor_analysis import z_score_values
scored_tensor = z_score_values(tensor)
scored_tensor

array([[[2.57041206, 3.80774245, 5.2797281 , 3.24182069],
        [0.0567362 , 2.2566029 , 0.09687236, 1.03358441],
        [3.13355559, 0.25908205, 2.54718406, 2.3104333 ]],

       [[2.7185702 , 4.04274658, 2.0047988 , 2.4454032 ],
        [2.53301936, 2.65908186, 0.98292295, 2.19609246],
        [1.48633671, 0.78481514, 0.29459879, 1.86194856]]])

In [8]:
def z_score_old(A, subtract = True):
    '''Function that takes in the values tensor and z-scores it.'''
    B = np.zeros_like(A)
    for i in range(A.shape[2]):
        slice_face = A[:,:,i]
        mu = np.mean(slice_face)
        sigma = np.std(slice_face)
        if subtract is True:
            z_scored_slice = (slice_face - mu) / sigma
        elif subtract is False:
            z_scored_slice = slice_face / sigma
        B[:,:,i] = z_scored_slice
    return B

In [9]:
scored_old_tensor = z_score_old(tensor, subtract = False)
scored_old_tensor

array([[[1.36264937, 2.18097573, 2.72706079, 3.68816626],
        [0.06136794, 2.63717152, 0.10208998, 2.39920533],
        [3.11545278, 0.27830627, 2.46743652, 4.92966418]],

       [[1.44119226, 2.31557997, 1.03550942, 2.78209514],
        [2.73980623, 3.10752723, 1.03586392, 5.09767438],
        [1.47775002, 0.84304943, 0.28537545, 3.97275313]]])